<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE Ap-Hospital[
<!ELEMENT Ap-Hospital (patient)>
<!ELEMENT patient (age,disease,date)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT disease (#PCDATA)>
<!ELEMENT date (#PCDATA)>

]>

<Ap-Hospital>
<patient id="Maha">
<age>21</age>
<disease>Fever</disease>
<date>2022-10-1</date>
 </patient>
<patient id="Neha">
 <age>61</age>
 <disease>Headache</disease>
 <date>2022-16-1</date>
 </patient>
 <patient id="Urooj">
  <age>90</age>
 <disease>flu</disease>
  <date>2022-20-1</date>
  </patient>
</Ap-Hospital>
  

